export enum PERMISSIONS {
  READ_PROFILE = 'read_profile',
  UDPATE_PROFILE = 'update_profile',
  CREATE_FORM = 'create_form',
  UPDATE_FORM = 'update_form',
  SUBMIT_FORM = 'submit_form',
  READ_FORM = 'read_form',
  APPROVE_FORM = 'approve_form',
  DELETE_FORM = 'delete_form',
  DELETE_USER = 'delete_user',
  CREATE_ROLE = 'create_role',
  DELETE_ROLE = 'delete_role',
  CREATE_PERMISSION = 'create_permission',
  DELETE_PERMISSION = 'delete_permission',
  UPDATE_PERMISSION = 'update_permission',
  CLOSE_FORM = 'close_form',
  READ_ALL_FORM = 'read_all_form',
}
